title: "我的博客"
description: "学习 & 分享"
theme: minimal
url: "https://yourname.github.io"
markdown: kramdown
author:
  name: "Adam"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

