site_name: 我的文档站
site_description: 用 MkDocs + Material 构建的 Markdown 站点
site_author: 你的名字
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.instant
    - search.highlight
    - search.suggest
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
nav:
  - 首页: index.md
  - 使用指南: guide.md
